version: 2.1
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - run:
        name: Versions
        command: npm version
      - checkout
      - run:
          name: Run a test
          command: npm test