version: 2.1
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run a test
          command: npm test